from django.shortcuts import render
import random 


def password_generate(request):
    characters = list('QWERTYUIOPASDFGHJKLZXCVBNM') # uppercase generated by default 

    if request.GET.get('lowercase'):
        characters.extend(list('qwertyuiopasdfghjklzxcvbnm'))

    if request.GET.get('numbers'):
        characters.extend(list('9876543210'))

    if request.GET.get('special'):
        characters.extend(list('!@#$%^&*-+{(])}<?>[,.:;\`/'))

    password = ''
    length = int(request.GET.get('length',8))

    i=0
    while i < length:
        password += random.choice(characters)
        i += 1 

    context_var = {'password':password,'length':length}
    return render(request,'password_generate.html',context_var)

    

