from django.shortcuts import render
import random 


def password_generate(request):
    characters = list('QWERTYUIOPASDFGHJKLZXCVBNM') # uppercase generated by default 

    if request.GET.get('lowercase'):
        characters.extend(list('qwertyuiopasdfghjklzxcvbnm'))

    if request.GET.get('numbers'):
        characters.extend(list('9876543210'))

    if request.GET.get('special'):
        characters.extend(list('!@#$%^&*-+{(])}<?>[,.:;\`/'))

    length = int(request.GET.get('length',8))

    password = ''.join(random.choice(characters) for _ in range(length))
    context_var = {'password':password,'length':length}
    return render(request,'password_generate.html',context_var)

    

